### ISSUE TITLE
自动解锁解禁能加个在私聊解禁的吗

### ISSUE THREAD

**Issue by axlmly** [ilharp/koishi-plugin-verify#1]

**Comment by ilharp** [comment]
私聊解禁的话希望通过什么样的形式解禁呢？我目前想到的形式有：

- 私聊发送 `unban` 指令解禁
- 在「指令管理」页面添加 `unban` 指令的别名，如 `解禁`，这样可以实现发送 `解禁` 进行解禁

还需要有什么其他可行的方式吗？

**Comment by axlmly** [comment]
> 私聊解禁的话希望通过什么样的形式解禁呢？我目前想到的形式有：
> 
> - 私聊发送 `unban` 指令解禁
> - 在「指令管理」页面添加 `unban` 指令的别名，如 `解禁`，这样可以实现发送 `解禁` 进行解禁
> 
> 还需要有什么其他可行的方式吗？
> 

我想到的是类似于bind一样给出一串验证码，可以是图片，当用户回复成功后可解禁
